### ISSUE TITLE
The image parrotsec/tools-metasploit doesn't work

### ISSUE THREAD

**Issue by gachampiat** [ParrotSec/docker-images#12]
Hi,

It seems that the docker image stored in docker hub
(https://hub.docker.com/r/parrotsec/tools-metasploit) doesn't work. As
you can see below I have an error when the container starts

```
podman run --rm -it --name test docker.io/parrotsec/tools-metasploit
    /bin/sh: 1: msfconsole-start: not found

sudo docker run --rm -ti parrotsec/tools-metasploit
    Unable to find image 'parrotsec/tools-metasploit:latest' locally
    latest: Pulling from parrotsec/tools-metasploit
    250c4d9991f5: Pull complete
    a5f5dddb8ddc: Pull complete
    ad73c1064879: Pull complete
    6a9c4ece880d: Pull complete
    Digest:
sha256:6292bb11e5f11520e1c2bf91ed23fc1c7a3099bba1215ef69cca3026ce034455
    Status: Downloaded newer image for parrotsec/tools-
metasploit:latest
    /bin/sh: 1: msfconsole-start: not found

```
Based on your Makefile, the image metasploit is based on nmap

```
tools-metasploit: tools-nmap
        docker build -t parrotsec/tools-metasploit:latest
tools/metasploit
```

So I have built the image through the Containerfile available here
https://github.com/ParrotSec/docker-images/blob/master/tools/metasploit/Dockerfile

Curiously when I create a container with my local build, the container
works correctly.

```
podman run --rm -it localhost/test
        Starting PostgreSQL 13 database server: main.
        [........]
        msf6 > db_status
        [*] Connected to msf. Connection type: postgresql.
```

 I have notive that the images don't have the same size

```
docker.io/parrotsec/tools-metasploit      latest  abdace9aa3a8  8 weeks
ago    4.07 GB
localhost/metasploit                      latest  cd5f06587d2e  28
hours ago   3.69 GB
```

Have you an idea ? Do you know why ? 

Thanks

**Comment by anthonytwh** [comment]
Running into the same problem with the parrotsec/tools-metasploit image

```
└──╼ #sh msfconsole-start 
postgresql: unrecognized service
msfconsole-start: 3: msfdb: not found
msfconsole-start: 4: msfdb: not found
msfconsole-start: 5: msfd: not found
msfconsole-start: 6: msfconsole: not found
```

@PalinuroSec

**Comment by PalinuroSec** [comment]
may i ask you why using sh before msfconsole-start? it might alter the $PATH variable. anyways i will trigger an image rebuild as soon as possible to fix the bug

**Comment by anthonytwh** [comment]
> may i ask you why using sh before msfconsole-start? it might alter the $PATH variable. anyways i will trigger an image rebuild as soon as possible to fix the bug

Thank you. Running with bash showed the same:

```
└──╼ #bash msfconsole-start 
postgresql: unrecognized service
msfconsole-start: line 3: msfdb: command not found
msfconsole-start: line 4: msfdb: command not found
msfconsole-start: line 5: msfd: command not found
msfconsole-start: line 6: msfconsole: command not found
```

**Comment by PalinuroSec** [comment]
ok then the image is totally broken, let me rebuild it

**Comment by PalinuroSec** [comment]
sorry for the long wait, but i take advantage of this weekend to ship the latest version of metasploit too. the new image is being uploaded right now
