### ISSUE TITLE
Unusable due mit mirror errors

### ISSUE THREAD

**Issue by bannsec** [ParrotSec/docker-images#13]
Have been attempting to use the parrotsec base docker image for unit testing with stegoveritas. Unfortunately, all it does it fail because the mit mirror returns 404 for everything. Easy to reproduce by simply running the latest docker, apt update then attempt to do anything (parrot-upgrade, apt dist-upgrade, apt-full upgrade, apt install python3, etc).

Will simply be removing this from testing for now, but would be good for you guys to ensure your primary mirrors work as i'm likely not the only person who gets bit by things like this.

**Comment by PalinuroSec** [comment]
hello, i have noticed it as well, it should be fixed now.

it seemed to be an error on our end while uploading the index list to our mirror redirectors. a stupid race condition between 2 concurrent upload attempts
