### ISSUE TITLE
Dock Installed

### ISSUE THREAD

**Issue by DanitiKain** [ParrotSec/docker-images#2]
I did apt-get install docker and then when I run any of docker commands listed on github it says command not found.

**Comment by subfission** [comment]
What is you host OS and are you installing docker into the host?

This works just fine for me...

**Comment by DanitiKain** [comment]
had to install sudo apt install docker-ce someone in TG group helped me.

**Comment by PalinuroSec** [comment]
"docker" is a docking application (like the mac os dock)

docker.io is the package you need to install in order to use the docker container engine



sudo apt update
sudo apt purge docker
sudo apt install docker.io
