### ISSUE TITLE
There aren't a lot of tools. Why don't you upload a full parrot image with all tools?

### ISSUE THREAD

**Issue by All3xJ** [ParrotSec/docker-images#9]
I noticed that anonsurf is missing, then I noticed that in all the images there are actually only few tools. Why don't you upload a full parrot os image with all the tools?

**Comment by PalinuroSec** [comment]
because some of them are GUI tools that make no sense inside a docker container, and some others are handled by the init system, which is not available inside a docker container, and a dedicated container with special rules is needed to start them properly

btw we are here to make it better
